[tool.black]
target-version = ['py311']
line-length = 79
exclude = '''
/(
        \.git
)/
'''

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "notes_project.settings"
