# Generated by Django 4.2.9 on 2024-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=140, verbose_name="Title"),
        ),
    ]
